Updated test

diff --git a/.github/workflows/account-service.yml b/.github/workflows/account-service.yml
--- a/.github/workflows/account-service.yml
+++ b/.github/workflows/account-service.yml
@@ -34,7 +34,14 @@ jobs:
         run: |
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-      - name: test with pytest
+      - name: Test with pytest
         run: |
-          pip install pytest
-          pytest
+          working-directory: account-service/backend/test
+          python -m pytest --verbose --junit-xml=junit.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/junit.xml'
+          detailed_summary: true
+          include_passed: true
